config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  get 'donate' => 'donate#index'

  get 'contact' => 'contact#index'

  get 'calendar' => 'calendar#index'

  get 'donate' => 'donate#index'

  get 'volunteer' => 'volunteer#index'

  get 'sh3' => 'events#sh3'

  get 'events' => 'events#index'

  get 'impact' => 'events#impact'

  devise_for :users
  resources :gallaries 
  resources :pictures
  
  resources :posts
  get 'about' => 'about#index'

   root 'posts#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :image,
    :path => "/images/:id/:style.:extension",
                  :url => ":s3_domain_url"

  do_not_validate_attachment_file_type :image
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   def index
   end

   def impact
   end

   def sh3
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: :new
	def index
		@posts = Post.all
	end	

	def new
		@post = Post.new 
	end

	def create  
		@post = Post.create(post_params)
		redirect_to posts_path 
	end  
	
	def show
		@post = Post.find(params[:id])
	end
	private

	def post_params  
		params.require(:post).permit(:title, :body)
	end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gallaries_helper.rb
module GallariesHelper
end

app/helpers/gallary_helper.rb
module GallaryHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/index.html.erb
   <!-- Carousel
    ================================================== -->

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag("griffin.jpg", :alt => "Blog") %>
          <div class="carousel-caption">
            <p><a class="btn btn-md btn-primary" href="events.html" role="button">Check out our blog below</a></p>
          </div>
        </div>
        <div class="item">
          <%= image_tag("Volunteer-copy.jpg", :alt => "Donate") %>
          <div class="carousel-caption">
            <p><a class="btn btn-md btn-primary" href="events.html" role="button">Volunteer</a></p>
          </div>
        </div>
      </div>
    </div>



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <%= image_tag ("imgF0"), class: "img-circle", alt: "Veterans Build", style: "width: 140px; height:140px;" %>
          <h2>Veteran's Build 2015</h2>
          <p>Join us in this years Veterans Day build to serve those who have served us.</p>
	  <p><%= link_to "View details", events_path, class: 'btn btn-primary' %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag ("img3F"), class: "img-circle", alt: "Veterans Build", style: "width: 140px; height:140px;" %>
          <h2>Safe Home Healthy Home</h2>
          <p>help make the difference in the lives of those who live near us.</p>
          <p><%= link_to "View details", sh3_path, class: 'btn btn-primary' %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag ("imgEE"), class: "img-circle", alt: "Veterans Build", style: "width: 140px; height:140px;" %>
          <h2>Impact<br>2016</h2>
          <p>In its 12 year, this year Impact will be held June 7-10.</p>
          <p><%= link_to "View details", impact_path, class: 'btn btn-primary' %></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
      <br>
      <div class="row text-center">
        <iframe src="http://www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fsquarefootministry&width&height=62&colorscheme=light&show_faces=false&header=false&stream=false&show_border=false" style="border:none;"></iframe>  
      </div>
      <% if user_signed_in? %>
         <%= link_to "New Post", new_post_path, class: 'btn btn-mini' %>
         <br> 
      <% end %>     
      <% @posts.reverse_each do |post| %>
      	<div class="jumbotron news-item">
          <h3 class="post-title">
              <%= post.title %>
          </h3>
          <p class="post-meta"><%= post.created_at.strftime("%b %d, %Y") %></p>
          <hr>
          <p class="post-item">
             <%= truncate post.body, length: 160  %>
          </p>
      
          
          <p><%=link_to "Read More", post, class: 'btn btn-primary' %></p>
     	</div>
 	  <% end -%>


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="./index.html">Back to top</a></p>
        <p>© 2015 Square Foot Ministry · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->
    <script src="./stylesheets/jquery.min.js"></script>
    <script src="./stylesheets/bootstrap.min.js"></script>
    <script src="./stylesheets/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="./stylesheets/ie10-viewport-bug-workaround.js"></script>
    <script>
    $('.carousel').carousel({
        interval: 2000 //changes the speed
    })
    </script>
    <div id="fb-root"></div>
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>

app/views/posts/new.html.erb
<div class="container">
	<div class="col-6">
		<div class="row">
    		<h1>New Post</h1>
		<%= simple_form_for @post do |f| %>
		  <%= f.input :title %>
		  <%= f.input :body %>
		  <%= f.button :submit %>
		<% end -%>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
<h3><%= @post.title %></h3>
<p><%= @post.body %></p>
</div>