config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  get 'donate' => 'donate#index'

  get 'contact' => 'contact#index'

  get 'calendar' => 'calendar#index'

  get 'donate' => 'donate#index'

  get 'volunteer' => 'volunteer#index'

  get 'sh3' => 'events#sh3'

  get 'events' => 'events#index'

  get 'impact' => 'events#impact'

  devise_for :users
  resources :gallaries 
  resources :pictures
  
  resources :posts
  get 'about' => 'about#index'

   root 'posts#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :image,
    :path => "/images/:id/:style.:extension",
                  :url => ":s3_domain_url"

  do_not_validate_attachment_file_type :image
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   def index
   end

   def impact
   end

   def sh3
   end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
	def create
	  @gallery = Gallery.new(gallery_params)

	  respond_to do |format|
	    if @gallery.save
	     
	      if params[:images]
		#===== The magic is here ;)
		params[:images].each { |image|
		  @gallery.pictures.create(image: image)
		}
	      end

	      format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
	      format.json { render json: @gallery, status: :created, location: @gallery }
	    else
	      format.html { render action: "new" }
	      format.json { render json: @gallery.errors, status: :unprocessable_entity }
	    end
	  end
	end
  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: :new
	def index
		@posts = Post.all
	end	

	def new
		@post = Post.new 
	end

	def create  
		@post = Post.create(post_params)
		redirect_to posts_path 
	end  
	
	def show
		@post = Post.find(params[:id])
	end
	private

	def post_params  
		params.require(:post).permit(:title, :body)
	end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gallaries_helper.rb
module GallariesHelper
end

app/helpers/gallary_helper.rb
module GallaryHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/galleries/_form.html.erb
<%= simple_form_for @gallery, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <div class="control-group">
    <div class="controls">
      <%= f.input :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.input :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galleries_path, :class => 'btn btn-mini' %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<div class="container">
	<h1>Editing Gallery</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @gallery %> |
	<%= link_to 'Back', galleries_path %>
</div>

app/views/galleries/index.html.erb
<div class="container">
  <div class="row">
    <h1>Galleries</h1>
    <% if user_signed_in? %>  
      <%= link_to 'New', new_gallery_path, :class => 'btn btn-mini' %>
    <% end %>    
    <p></p>
	<% @galleries.reverse.each do |gallery| %>       
            <div class="gallery-container">
              <% if gallery.pictures.first %>
		<p id="gallery-title"><%= gallery.name %></p>  
                <%= link_to image_tag(gallery.pictures.first.image.url), gallery_path(gallery), :class => 'gallery' %>
              <% else %>
                N/A
              <% end %>
              <div class="caption">
                <p style="text-align: center;">
                <% if user_signed_in? %> 
                  <%= link_to "Show", gallery_path(gallery) %>
                  <%= link_to "Edit", edit_gallery_path(gallery) %>
                  <%= link_to "Delete", gallery,
                    :data => { :confirm => "Are you sure?" },
                    :method => :delete
                  %>
 		<% end %>              
                </p>
              </div>
            </div>
      <% end %>
  </div>
</div>

app/views/galleries/new.html.erb
<div class="container">
	<h1>New Gallery</h1>

	<%= render 'form' %>

	<%= link_to 'Back', galleries_path %>
</div>

app/views/galleries/show.html.erb
<div class="container">
	<div class="row">
	  <h1><%= @gallery.name %></h1>

	  <input type="hidden" id="galleryID" value="<%= @gallery.id %>">

	  <p>
	    <b>Description </b>
	    <%= @gallery.description %>
	  </p>
	  <% if user_signed_in? %>
		  <div class="form-actions">
		    <%= link_to 'Back', galleries_path, :class => 'btn btn-mini'  %>
		    <%= link_to 'Edit gallery', edit_gallery_path(@gallery), :class => 'btn btn-mini' %>
		    <%= link_to 'Delete gallery', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
		  </div>
	  <% end -%>
	</div>

	<div class="row">
	  <% @gallery.pictures.reverse.each do |pic| %>
	    <div class="thumbnail">
	      <%= image_tag pic.image.url %>
	      <div class="caption">
		<p style="text-align: center;">
		</p>
	      </div>
	    </div>
	  <% end %>
	</div>
</div>