config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  get 'donate' => 'donate#index'

  get 'contact' => 'contact#index'

  get 'calendar' => 'calendar#index'

  get 'donate' => 'donate#index'

  get 'volunteer' => 'volunteer#index'

  get 'sh3' => 'events#sh3'

  get 'events' => 'events#index'

  get 'impact' => 'events#impact'

  devise_for :users
  resources :gallaries 
  resources :pictures
  
  resources :posts
  get 'about' => 'about#index'

   root 'posts#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :image,
    :path => "/images/:id/:style.:extension",
                  :url => ":s3_domain_url"

  do_not_validate_attachment_file_type :image
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   def index
   end

   def impact
   end

   def sh3
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: :new
	def index
		@posts = Post.all
	end	

	def new
		@post = Post.new 
	end

	def create  
		@post = Post.create(post_params)
		redirect_to posts_path 
	end  
	
	def show
		@post = Post.find(params[:id])
	end
	private

	def post_params  
		params.require(:post).permit(:title, :body)
	end  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gallaries_helper.rb
module GallariesHelper
end

app/helpers/gallary_helper.rb
module GallaryHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Square Foot Ministry - Becoming Tools Of God's Love One Square Foot At A Time.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <style type="text/css">
      .navbar-default .navbar-fixed-top .navbar {
        border-radius: 0px;
      }
      .news-item {
        -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
        padding-top: 15px;
        padding-bottom: 30px;
      }
    </style>
</head>
<body>
    <div class="navbar-wrapper">
      <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <div class="navbar-header">
                <%= image_tag ("sfm2.png"), style: "max-width:290px; margin-top:-7px;" %>
              </div>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Volunteer", volunteer_path %></li>
                <li><%= link_to "Donate", donate_path %></li>
                <li><%= link_to "Calendar", calendar_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Gallery", galleries_path %><li>
	        <% if user_signed_in? %>
			<li><%= link_to "Signout", destroy_user_session_path, :method => 'delete' %></li>
	        <% end %>	
	      </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
<%= yield %>
<div id="global-zeroclipboard-html-bridge" class="global-zeroclipboard-container" style="position: absolute; left: 0px; top: -9999px; width: 15px; height: 15px; z-index: 999999999;" title="" data-original-title="Copy to clipboard">      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="global-zeroclipboard-flash-bridge" width="100%" height="100%">         <param name="movie" value="/assets/flash/ZeroClipboard.swf?noCache=1417049500632">         <param name="allowScriptAccess" value="sameDomain">         <param name="scale" value="exactfit">         <param name="loop" value="false">         <param name="menu" value="false">         <param name="quality" value="best">         <param name="bgcolor" value="#ffffff">         <param name="wmode" value="transparent">         <param name="flashvars" value="trustedOrigins=getbootstrap.com%2C%2F%2Fgetbootstrap.com%2Chttp%3A%2F%2Fgetbootstrap.com">         <embed src="/assets/flash/ZeroClipboard.swf?noCache=1417049500632" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="100%" height="100%" name="global-zeroclipboard-flash-bridge" allowscriptaccess="sameDomain" allowfullscreen="false" type="application/x-shockwave-flash" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="trustedOrigins=getbootstrap.com%2C%2F%2Fgetbootstrap.com%2Chttp%3A%2F%2Fgetbootstrap.com" scale="exactfit">                </object></div><svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500" preserveAspectRatio="none" style="visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs></defs><text x="0" y="23" style="font-weight:bold;font-size:23pt;font-family:Arial, Helvetica, Open Sans, sans-serif;dominant-baseline:middle">500x500</text></svg>

</body>
</html>